apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: productmicroservice
  name: productmicroservice
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: productmicroservice
status:
  loadBalancer: {}